inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/locales/*'
    - 'features/*/*'